// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct Package : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static Package GetRootAsPackage(ByteBuffer _bb) { return GetRootAsPackage(_bb, new Package()); }
  public static Package GetRootAsPackage(ByteBuffer _bb, Package obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Package __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MessageKind Kind { get { int o = __p.__offset(4); return o != 0 ? (MessageKind)__p.bb.GetUshort(o + __p.bb_pos) : MessageKind.StartGame; } }
  public DataPack DataType { get { int o = __p.__offset(6); return o != 0 ? (DataPack)__p.bb.Get(o + __p.bb_pos) : DataPack.NONE; } }
  public TTable? Data<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(8); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }

  public static Offset<Package> CreatePackage(FlatBufferBuilder builder,
      MessageKind kind = MessageKind.StartGame,
      DataPack data_type = DataPack.NONE,
      int dataOffset = 0) {
    builder.StartTable(3);
    Package.AddData(builder, dataOffset);
    Package.AddKind(builder, kind);
    Package.AddDataType(builder, data_type);
    return Package.EndPackage(builder);
  }

  public static void StartPackage(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddKind(FlatBufferBuilder builder, MessageKind kind) { builder.AddUshort(0, (ushort)kind, 0); }
  public static void AddDataType(FlatBufferBuilder builder, DataPack dataType) { builder.AddByte(1, (byte)dataType, 0); }
  public static void AddData(FlatBufferBuilder builder, int dataOffset) { builder.AddOffset(2, dataOffset, 0); }
  public static Offset<Package> EndPackage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Package>(o);
  }
  public static void FinishPackageBuffer(FlatBufferBuilder builder, Offset<Package> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPackageBuffer(FlatBufferBuilder builder, Offset<Package> offset) { builder.FinishSizePrefixed(offset.Value); }
};

