// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace messages
{

using global::System;
using global::FlatBuffers;

public struct InputEmpty : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static InputEmpty GetRootAsInputEmpty(ByteBuffer _bb) { return GetRootAsInputEmpty(_bb, new InputEmpty()); }
  public static InputEmpty GetRootAsInputEmpty(ByteBuffer _bb, InputEmpty obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public InputEmpty __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public messages.InputKind Kind { get { int o = __p.__offset(4); return o != 0 ? (messages.InputKind)__p.bb.GetShort(o + __p.bb_pos) : messages.InputKind.Start; } }

  public static Offset<messages.InputEmpty> CreateInputEmpty(FlatBufferBuilder builder,
      messages.InputKind kind = messages.InputKind.Start) {
    builder.StartTable(1);
    InputEmpty.AddKind(builder, kind);
    return InputEmpty.EndInputEmpty(builder);
  }

  public static void StartInputEmpty(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddKind(FlatBufferBuilder builder, messages.InputKind kind) { builder.AddShort(0, (short)kind, 0); }
  public static Offset<messages.InputEmpty> EndInputEmpty(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<messages.InputEmpty>(o);
  }
};


}
