// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace messages
{

public enum InputKind : short
{
  Start = 0,
  Reset = 1,
};


}
