// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace messages
{

using global::System;
using global::FlatBuffers;

public struct OutputEmpty : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static OutputEmpty GetRootAsOutputEmpty(ByteBuffer _bb) { return GetRootAsOutputEmpty(_bb, new OutputEmpty()); }
  public static OutputEmpty GetRootAsOutputEmpty(ByteBuffer _bb, OutputEmpty obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public OutputEmpty __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public messages.OutputKind Kind { get { int o = __p.__offset(4); return o != 0 ? (messages.OutputKind)__p.bb.GetShort(o + __p.bb_pos) : messages.OutputKind.Started; } }

  public static Offset<messages.OutputEmpty> CreateOutputEmpty(FlatBufferBuilder builder,
      messages.OutputKind kind = messages.OutputKind.Started) {
    builder.StartTable(1);
    OutputEmpty.AddKind(builder, kind);
    return OutputEmpty.EndOutputEmpty(builder);
  }

  public static void StartOutputEmpty(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddKind(FlatBufferBuilder builder, messages.OutputKind kind) { builder.AddShort(0, (short)kind, 0); }
  public static Offset<messages.OutputEmpty> EndOutputEmpty(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<messages.OutputEmpty>(o);
  }
};


}
