// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace messages
{

public enum OutputKind : short
{
  Started = 0,
  Reseted = 1,
  Created = 2,
  Updated = 3,
  Removed = 4,
};


}
