// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace messages
{

using global::System;
using global::FlatBuffers;

public struct Users : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static Users GetRootAsUsers(ByteBuffer _bb) { return GetRootAsUsers(_bb, new Users()); }
  public static Users GetRootAsUsers(ByteBuffer _bb, Users obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Users __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<messages.Users> CreateUsers(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(1);
    Users.AddName(builder, nameOffset);
    return Users.EndUsers(builder);
  }

  public static void StartUsers(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static Offset<messages.Users> EndUsers(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<messages.Users>(o);
  }
  public static void FinishUsersBuffer(FlatBufferBuilder builder, Offset<messages.Users> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedUsersBuffer(FlatBufferBuilder builder, Offset<messages.Users> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
