// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace responses
{

using global::System;
using global::FlatBuffers;

public struct EmptyPackage : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public EmptyPackage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public responses.ResponseKind Kind { get { return (responses.ResponseKind)__p.bb.GetUshort(__p.bb_pos + 0); } }

  public static Offset<responses.EmptyPackage> CreateEmptyPackage(FlatBufferBuilder builder, responses.ResponseKind Kind) {
    builder.Prep(2, 2);
    builder.PutUshort((ushort)Kind);
    return new Offset<responses.EmptyPackage>(builder.Offset);
  }
};


}
