// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FfiRequests
{

public enum RequestKind : ushort
{
  GameStatus = 0,
  StartGame = 1,
  GetAll = 2,
  SetInputAxis = 3,
};


}
