// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FfiRequests
{

using global::System;
using global::FlatBuffers;

public struct Requests : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static Requests GetRootAsRequests(ByteBuffer _bb) { return GetRootAsRequests(_bb, new Requests()); }
  public static Requests GetRootAsRequests(ByteBuffer _bb, Requests obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Requests __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FfiRequests.V2Package? Axis { get { int o = __p.__offset(4); return o != 0 ? (FfiRequests.V2Package?)(new FfiRequests.V2Package()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartRequests(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddAxis(FlatBufferBuilder builder, Offset<FfiRequests.V2Package> axisOffset) { builder.AddStruct(0, axisOffset.Value, 0); }
  public static Offset<FfiRequests.Requests> EndRequests(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FfiRequests.Requests>(o);
  }
};


}
