// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FfiRequests
{

public enum RequestKind : ushort
{
  SetInputAxis = 0,
};


}
