[package]
name = "rustlib"
version = "0.1.0"
authors = ["sisso <sisso@sisso.com.br>"]
edition = "2018"

# need to be commented to run example or tests :/
[lib]
name="rustlib"
crate-type = ["lib", "cdylib"]

[dependencies]
libc = "*"
flatbuffers = "*"
