// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace server
{

public enum ChangeKind : ushort
{
  Spawn = 0,
  Pos = 1,
  GenericU32 = 2,
  GenericI32 = 3,
  GenericStr = 4,
  GenericF32 = 5,
};


}
