// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace server
{

public enum PackageKind : sbyte
{
  RequestLogin = 0,
  ResponseLogin = 1,
  RequestChange = 2,
  ResponseChange = 3,
};


}
