// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FfiPackages
{

public enum PackageKind : ushort
{
  Request = 0,
  Response = 1,
};


}
