// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum DataPack : byte
{
  NONE = 0,
  IdPackage = 1,
  PosPackage = 2,
  StringPackage = 3,
  BytesPackage = 4,
};

