// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct EmptyPackage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static EmptyPackage GetRootAsEmptyPackage(ByteBuffer _bb) { return GetRootAsEmptyPackage(_bb, new EmptyPackage()); }
  public static EmptyPackage GetRootAsEmptyPackage(ByteBuffer _bb, EmptyPackage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EmptyPackage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MessageKind Kind { get { int o = __p.__offset(4); return o != 0 ? (MessageKind)__p.bb.GetUshort(o + __p.bb_pos) : MessageKind.StartGame; } }

  public static Offset<EmptyPackage> CreateEmptyPackage(FlatBufferBuilder builder,
      MessageKind kind = MessageKind.StartGame) {
    builder.StartTable(1);
    EmptyPackage.AddKind(builder, kind);
    return EmptyPackage.EndEmptyPackage(builder);
  }

  public static void StartEmptyPackage(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddKind(FlatBufferBuilder builder, MessageKind kind) { builder.AddUshort(0, (ushort)kind, 0); }
  public static Offset<EmptyPackage> EndEmptyPackage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<EmptyPackage>(o);
  }
};

