// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum GenericPackage : byte
{
  NONE = 0,
  EmptyPackage = 1,
  SimplePackage = 2,
};

