// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct Input : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_11_1(); }
  public static Input GetRootAsInput(ByteBuffer _bb) { return GetRootAsInput(_bb, new Input()); }
  public static Input GetRootAsInput(ByteBuffer _bb, Input obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Input __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public V2Package? Axis { get { int o = __p.__offset(4); return o != 0 ? (V2Package?)(new V2Package()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartInput(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddAxis(FlatBufferBuilder builder, Offset<V2Package> axisOffset) { builder.AddStruct(0, axisOffset.Value, 0); }
  public static Offset<Input> EndInput(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Input>(o);
  }
};

