// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum MessageKind : ushort
{
  StartGame = 0,
  CreateObj = 1,
  MoveObj = 2,
  SetInputAxis = 3,
};

