// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FfiResponses
{

using global::System;
using global::FlatBuffers;

public struct CreatePackage : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public CreatePackage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public FfiResponses.PrefabKind Prefab { get { return (FfiResponses.PrefabKind)__p.bb.GetUshort(__p.bb_pos + 4); } }
  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }

  public static Offset<FfiResponses.CreatePackage> CreateCreatePackage(FlatBufferBuilder builder, uint Id, FfiResponses.PrefabKind Prefab, float X, float Y) {
    builder.Prep(4, 16);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    builder.Pad(2);
    builder.PutUshort((ushort)Prefab);
    builder.PutUint(Id);
    return new Offset<FfiResponses.CreatePackage>(builder.Offset);
  }
};


}
