// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FfiResponses
{

using global::System;
using global::FlatBuffers;

public struct EmptyPackage : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public EmptyPackage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FfiResponses.ResponseKind Kind { get { return (FfiResponses.ResponseKind)__p.bb.GetUshort(__p.bb_pos + 0); } }
  public uint Ordering { get { return __p.bb.GetUint(__p.bb_pos + 4); } }

  public static Offset<FfiResponses.EmptyPackage> CreateEmptyPackage(FlatBufferBuilder builder, FfiResponses.ResponseKind Kind, uint Ordering) {
    builder.Prep(4, 8);
    builder.PutUint(Ordering);
    builder.Pad(2);
    builder.PutUshort((ushort)Kind);
    return new Offset<FfiResponses.EmptyPackage>(builder.Offset);
  }
};


}
