// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FfiResponses
{

using global::System;
using global::FlatBuffers;

public struct PosPackage : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public PosPackage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

  public static Offset<FfiResponses.PosPackage> CreatePosPackage(FlatBufferBuilder builder, uint Id, float X, float Y) {
    builder.Prep(4, 12);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    builder.PutUint(Id);
    return new Offset<FfiResponses.PosPackage>(builder.Offset);
  }
};


}
