// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FfiResponses
{

public enum PrefabKind : ushort
{
  Player = 0,
  Monster = 1,
};


}
