// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FfiResponses
{

public enum ResponseKind : ushort
{
  GameStarted = 0,
  GameStatusIdle = 1,
  GameStatusRunning = 2,
  FullStateResponse = 3,
  CreateObj = 4,
  MoveObj = 5,
};


}
