// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FfiResponses
{

public enum ResponseKind : ushort
{
  StartGame = 0,
  CreateObj = 1,
  MoveObj = 2,
};


}
