// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FfiResponses
{

public enum ResponseKind : ushort
{
  CreateObj = 0,
  MoveObj = 1,
};


}
